# -*- coding: utf-8 -*-
"""=task_03_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vqjMyKBJOeegKaY0Tx2_t_iD0zlooFp
"""

import numpy as np
import pandas as pd

# 12,000 rows ka synthetic raw dataset create karna
np.random.seed(42)
n_rows = 12000

data = {
    "Transaction_ID": [f"TXN_{i}" for i in range(1, n_rows + 1)],
    "Date": pd.date_range("2024-01-01", periods=n_rows, freq="30min")
    .astype(str)
    .values,
    "Customer_ID": np.random.choice(
        [f"CUST_{i}" for i in range(100, 500)], size=n_rows
    ),
    "Category": np.random.choice(
        ["Electronics", "Apparel", "Home Goods", None],
        size=n_rows,
        p=[0.4, 0.35, 0.2, 0.05],
    ),
    "Quantity": np.random.choice([1, 2, 3, 4, 5, -2, 999], size=n_rows),
    "Unit_Price": np.random.uniform(15.0, 600.0, size=n_rows).round(2),
    "Cost_Price": np.random.uniform(10.0, 350.0, size=n_rows).round(2),
}

df = pd.DataFrame(data)

# Real-world mess inject karna: Duplicates, null values, invalid dates
df = pd.concat([df, df.iloc[:150]], ignore_index=True)  # 150 duplicate rows
df.loc[15:45, "Unit_Price"] = np.nan  # Missing prices
df.loc[60:75, "Date"] = "invalid_timestamp"  # Corrupt date strings

# Optional: Raw copy export karna (agar record rakhna ho)
df.to_csv("raw_dataset.csv", index=False)
print("Raw dataset ready! Shape:", df.shape)

print("=== BEFORE CLEANING AUDIT ===")
print("Initial Shape:", df.shape)
print("\n--- Column Info & Data Types ---")
df.info()

print("\n--- Missing Values Count ---")
print(df.isnull().sum())

print("\n--- Duplicate Rows Count ---")
print("Duplicates:", df.duplicated().sum())

print("\n--- Outlier Check (Quantity) ---")
print(df["Quantity"].describe())

# 1. Remove duplicate records
df = df.drop_duplicates().reset_index(drop=True)

# 2. Fix corrupt dates & parse datetime
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna(subset=["Date"]).reset_index(drop=True)

# 3. Handle missing values
df["Category"] = df["Category"].fillna("Unknown")

# Unit_Price missing values ko median se fill karna (per Category)
df["Unit_Price"] = df.groupby("Category")["Unit_Price"].transform(
    lambda x: x.fillna(x.median())
)

# 4. Outlier removal: Quantity valid range (1 se 20 units)
df = df[(df["Quantity"] > 0) & (df["Quantity"] <= 20)].reset_index(drop=True)

print("Cleaning complete! Rows remaining:", len(df))

# 1. Date features extract karna
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.strftime("%B")
df["Day_Name"] = df["Date"].dt.strftime("%A")

# 2. Financial metrics calculate karna
df["Revenue"] = (df["Quantity"] * df["Unit_Price"]).round(2)
df["Total_Cost"] = (df["Quantity"] * df["Cost_Price"]).round(2)
df["Profit"] = (df["Revenue"] - df["Total_Cost"]).round(2)

# Profit margin percentage: (Profit / Revenue) * 100
df["Profit_Margin_Pct"] = ((df["Profit"] / df["Revenue"]) * 100).round(2)

df[
    [
        "Transaction_ID",
        "Date",
        "Month_Name",
        "Revenue",
        "Profit",
        "Profit_Margin_Pct",
    ]
].head()

print("=== AFTER CLEANING AUDIT ===")
print("Final Shape:", df.shape)
print("\nMissing values remaining:\n", df.isnull().sum())
print("\nFinal Data Types:")
print(df.dtypes)

# Task deliverable export karna
df.to_csv("clean_dataset.csv", index=False)
print("\nFile successfully saved as 'clean_dataset.csv'!")